# Generated by Django 5.2 on 2025-05-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='picture',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
